LIMIT = 100
TIMEOUT = 1
DB_PATH = "data/redmine_source"
ATTACHMENTS_PATH = "data/attachments"
HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"}
FILE_TYPES = ("pdf", "doc", "docx", "ppt", "pptx", "xls", "xlsx", "txt", "sql")
TRACKER_ID = {"1": "defect", "2": "feature", "3": "patch", "4": "complete"}
PAGE_LIMIT = 10
SAMPLE_PROJECTS = [
    {'id': 21, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 4, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 15, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 5, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 6, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 11, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 7, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 19, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 9, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 17, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 10, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 12, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 22, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 2, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 23, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 1, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 24, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 8, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 3, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 14, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 16, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 25, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 18, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 13, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
    {'id': 20, 'name': 'Redmine', 'identifier': 'redmine', 'description': 'Redmine is a flexible project management web application written using Ruby on Rails framework.', 'status': 1, 'is_public': True, 'inherit_members': False, 'created_on': '2007-09-29T10:03:04Z', 'updated_on': '2009-03-15T11:35:11Z'},
]